Common_Lottery_Text_LotteryCornerDrawTicket:
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers at our DEPARTMENT STORE\n"
	.string "get to draw a POKéMON LOTO TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your POKéMON,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"

Common_Lottery_Text_ComeBackTomorrow:
	.string "Please come back tomorrow.$"

Common_Lottery_Text_PleaseVisitAgain:
	.string "Please do visit again.$"

Common_Lottery_Text_PleasePickTicket:
	.string "Please pick a LOTO TICKET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

Common_Lottery_Text_TicketNumberIsXPleaseWait:
	.string "The LOTO TICKET number is {STR_VAR_1}.\p"
	.string "I need to run a check on this number\n"
	.string "to see if it matches any of your\l"
	.string "POKéMON's ID numbers. Please wait.$"

Common_Lottery_Text_TicketMatchesPartyMon:
	.string "Congratulations!\p"
	.string "The ID number of your team's\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

Common_Lottery_Text_TicketMatchesPCMon:
	.string "Congratulations!\p"
	.string "The ID number of your PC-boxed\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

Common_Lottery_Text_NoNumbersMatched:
	.string "I'm sorry.\n"
	.string "None of the numbers matched.$"

Common_Lottery_Text_TwoDigitsMatched:
	.string "Two digits matched, so you win the\n"
	.string "third prize!\l"
	.string "You've won the {STR_VAR_1}!$"

Common_Lottery_Text_ThreeDigitsMatched:
	.string "Three digits matched, so you win the\n"
	.string "second prize!\l"
	.string "You've won the {STR_VAR_1}!$"

Common_Lottery_Text_FourDigitsMatched:
	.string "Four digits matched, so you win the\n"
	.string "first prize!\l"
	.string "You've won the {STR_VAR_1}!$"

Common_Lottery_Text_AllFiveDigitsMatched:
	.string "Oh, my goodness, all five digits\n"
	.string "matched!\p"
	.string "You've won the jackpot prize!\n"
	.string "You've won the {STR_VAR_1}!$"

Common_Lottery_Text_NoRoomForThis:
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"

Common_Lottery_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Yes, I've been expecting you.\p"
	.string "This is the prize we've been holding\n"
	.string "for you.$"

Common_Lottery_Text_PleaseVisitAgain2:
	.string "Please do visit again.$"
